env:
  global:
  - DEBUG='* -superagent -express:* -mocha:*'
language: node_js
node_js:
- '0.12'
script: npm test
before_install:
- openssl aes-256-cbc -K $encrypted_bc9812f1b6a1_key -iv $encrypted_bc9812f1b6a1_iv
  -in taskcluster-base-test.conf.json.enc -out taskcluster-base-test.conf.json -d
